### ISSUE TITLE
Race condition in Docker 1.12.1-2.el7.centos between create-container and upload-to-container when using a volume

### ISSUE THREAD

**Issue by smarterclayton** [projectatomic/docker#207]
Seeing a race condition when I perform the following steps:
1. create-volume (local)
2. create-container with a bind mount of the volume into `/tmp/__temporary`
3. upload-to-container of an archive into `/tmp/__temporary/1` (which should go into the volume)

If I add a 10 second sleep between 2 and 3, it works.  Without the sleep it fails consistently on 1.12.1-2.el7.centos.  It works every time on 1.10 (no race, no sleep necessary).

To reproduce, check out https://github.com/openshift/imagebuilder/pull/14 and run:

```
go test ./dockerclient -tags conformance -test.run=TestTransientMount -test.v
```

You can add a `time.Sleep(10*time.Second)` to line 289 of `dockerclient/client.go` inside of `StartPartialContainer` to repro.

**Comment by smarterclayton** [comment]
@mrunalp as discussed online

**Comment by smarterclayton** [comment]
I tried another directory besides `/tmp` on the off chance it had something to do with that but no difference (neither /var nor arbitrary folder changed the problem)>

**Comment by runcom** [comment]
I'll try to reproduce and report upstream if necessary, thanks

**Comment by runcom** [comment]
That unit test just says "failed with exit code 1" - daemon logs shows:
```
Oct 20 01:20:15 localhost.localdomain docker[11487]: time="2016-10-20T01:20:15.412574186+02:00" level=error msg="Handler for DELETE /images/conformance5577006791947779410 returned error: No such image: conformance5577006791947779410:latest"
```

**Comment by smarterclayton** [comment]
You have to pull busybox first.  I pushed changes that fix that, but my
previous line number has changed (it's between the container create and the
copy)

**Comment by runcom** [comment]
> You have to pull busybox first.

I already have busybox :confused:

**Comment by runcom** [comment]
@smarterclayton I had no luck trying to repro this with just docker - https://gist.github.com/runcom/14c700d2d1b29e34a795685cb644d275 am I missing something?

**Comment by runcom** [comment]
> You have to pull busybox first.

@smarterclayton I also have busybox but I'm still getting the error in https://github.com/projectatomic/docker/issues/207#issuecomment-254968637

**Comment by runcom** [comment]
@mrunalp @smarterclayton with https://gist.github.com/runcom/14c700d2d1b29e34a795685cb644d275 I cannot reproduce on centos either. The tar is:
```
[root@centos ~]# tar tvf test.tar
drwxr-xr-x root/root         0 2016-10-25 14:54 ./
drwxr-xr-x root/root         0 2016-10-25 14:54 ./test/
-rw-r--r-- root/root         5 2016-10-25 14:53 ./test/ciaone
```
the only stuff I get in the logs is:
```
Oct 25 15:25:03 centos.vm dockerd-latest[9139]: time="2016-10-25T15:25:03.722735434Z" level=info msg="{Action=remove, Username=root, LoginUID=0, PID=25204}"
Oct 25 15:25:04 centos.vm dockerd-latest[9139]: time="2016-10-25T15:25:04.120346082Z" level=info msg="{Action=remove, Username=root, LoginUID=0, PID=25204}"
Oct 25 15:25:04 centos.vm dockerd-latest[9139]: time="2016-10-25T15:25:04.125635991Z" level=info msg="{Action=create, Username=root, LoginUID=0, PID=25204}"
Oct 25 15:25:04 centos.vm dockerd-latest[9139]: time="2016-10-25T15:25:04.134778897Z" level=info msg="{Action=create, Username=root, LoginUID=0, PID=25204}"
Oct 25 15:25:14 centos.vm dockerd-latest[9139]: time="2016-10-25T15:25:14.420337856Z" level=info msg="{Action=archive, Username=root, LoginUID=0, PID=25204}"
Oct 25 15:25:14 centos.vm dockerd-latest[9139]: time="2016-10-25T15:25:14.548954581Z" level=info msg="{Action=start, Username=root, LoginUID=0, PID=25204}"
Oct 25 15:25:14 centos.vm dockerd-latest[9139]: cat: can't open '/test/test': No such file or directory
```
Notice the last line above, maybe I'm still missing something...

**Comment by smarterclayton** [comment]
Shouldn't you be catting ./test/ciaone?

**Comment by runcom** [comment]
I'm cat(ing) that which should be at /test/ciaone (notice there's no dot before the first slash)

**Comment by runcom** [comment]
@smarterclayton I can finally run the program at https://gist.github.com/runcom/14c700d2d1b29e34a795685cb644d275 but no luck yet on racing... (testing on a centos box)

**Comment by smarterclayton** [comment]
Created a reproducer on my machine:

```
#!/bin/bash
set -ex
docker volume rm v1 || true
docker rm t1 t2 || true
docker volume create --name v1
docker create --name t1 -v v1:/.imagebuilder-transient-mount busybox
cat a.tar | docker cp - t1:/
cat b.tar | docker cp - t1:/
docker create --name t2 \
       -v $(docker volume inspect -f '{{ .Mountpoint }}' v1)/0:/mountdir \
       -v $(docker volume inspect -f '{{ .Mountpoint }}' v1)/1:/mountfile \
       busybox ls -al /
docker start -a t2
```

when run with the following in the same dir

[testfiles.zip](https://github.com/projectatomic/docker/files/551984/testfiles.zip)

I get 

```
+ docker start -a t2
total 24
drwxr-xr-x   15 root     root          4096 Oct 25 23:11 .
drwxr-xr-x   15 root     root          4096 Oct 25 23:11 ..
-rwxr-xr-x    1 root     root             0 Oct 25 23:11 .dockerenv
drwxr-xr-x    2 root     root          8192 Oct  7 18:18 bin
drwxr-xr-x    5 root     root           360 Oct 25 23:11 dev
drwxr-xr-x    2 root     root          4096 Oct 25 23:11 etc
drwxr-xr-x    2 nobody   nogroup          6 Oct  7 18:18 home
drwxr-xr-x    2 root     root             6 Oct 25 23:11 mountdir
drwxr-xr-x    2 root     root             6 Oct 25 23:11 mountfile
dr-xr-xr-x  192 root     root             0 Oct 25 23:11 proc
drwxr-xr-x    2 root     root             6 Oct  7 18:18 root
drwxr-xr-x    3 root     root            20 Oct 25 23:11 run
dr-xr-xr-x   13 root     root             0 Oct 24 03:03 sys
drwxrwxrwt    2 root     root             6 Oct  7 18:18 tmp
drwxr-xr-x    3 root     root            17 Oct  7 18:18 usr
drwxr-xr-x    4 root     root            28 Oct  7 18:18 var
```

everytime, when in 1.10 both mountfile was a file

**Comment by smarterclayton** [comment]
1.10:

```
+ docker start -a t2
total 28
drwxr-xr-x   14 root     root          4096 Oct 25 23:16 .
drwxr-xr-x   14 root     root          4096 Oct 25 23:16 ..
-rwxr-xr-x    1 root     root             0 Oct 25 23:16 .dockerenv
-rwxr-xr-x    1 root     root             0 Oct 25 23:16 .dockerinit
drwxr-xr-x    2 root     root          8192 Oct  7 18:18 bin
drwxr-xr-x    5 root     root           360 Oct 25 23:16 dev
drwxr-xr-x    2 root     root          4096 Oct 25 23:16 etc
drwxr-xr-x    2 nobody   nogroup          6 Oct  7 18:18 home
drwxr-xr-x    3 root     root            47 Oct 19 15:22 mountdir
-rw-r--r--    1 root     root           583 Oct 19 15:22 mountfile
dr-xr-xr-x  191 root     root             0 Oct 25 23:16 proc
drwxr-xr-x    2 root     root             6 Oct  7 18:18 root
drwxr-xr-x    3 root     root            20 Oct 25 23:16 run
dr-xr-xr-x   13 root     root             0 Oct 24 03:03 sys
drwxrwxrwt    2 root     root             6 Oct  7 18:18 tmp
drwxr-xr-x    3 root     root            17 Oct  7 18:18 usr
drwxr-xr-x    4 root     root            28 Oct  7 18:18 var
```

**Comment by smarterclayton** [comment]
Not even sure this is a race - just broken

**Comment by runcom** [comment]
Alright, debug so far

* it works on docker-1.12.1 in Fedora
* it fails on centos only (tested on centos with docker-latest)

**Comment by smarterclayton** [comment]
kernel problem?  implies a problem on RHEL too?

**Comment by runcom** [comment]
More debugging https://github.com/docker/docker/issues/27773

**Comment by runcom** [comment]
Fixed in docker master upstream. Going to backport to 1.12.3 tomorrow.

**Comment by runcom** [comment]
fixed by https://github.com/projectatomic/docker/commit/47e22f22361b3e4a73479b20d1f35f237ed8faba

**Comment by stevekuznetsov** [comment]
@runcom can you let me know either
 - which RPM release I can expect to see this in
 - how to determine the above information myself for any given commit in this repo

**Comment by rhatdan** [comment]
docker-1.12.4.* release most likely or if we don't update docker-1.10 in the next release docker-latest-1.12.4.*

**Comment by stevekuznetsov** [comment]
@runcom had mentioned 1.12.3 as well due to a backport -- do you know which patch that would be?

**Comment by runcom** [comment]
Docker 1.12.3 in Fedora and Docker-latest 1.12.3 in rhel should have this. As @rhatdan said, we're in the process of shipping 1.12.4 when it goes out upstream.

**Comment by stevekuznetsov** [comment]
@runcom to be clear, `docker-1.12.3-8` is what I have available -- are you saying `1.12.3-0` and newer all have it? Or is it a specific patch on top of `1.12.3`?

**Comment by runcom** [comment]
It's a specific patch on top of docker-1.12.3 - I believe rhel has it but now that I think more I'm not sure anymore. If you have any specific rhel version you want me to check to this included please tell me it here and I'll check ASAP.

**Comment by stevekuznetsov** [comment]
Today I have access to `docker-1.12.3-8` on Troy's repo on the OpenShift mirror. Will that have the fix?

**Comment by stevekuznetsov** [comment]
Specifically, `docker-1.12.3-8.el7.x86_64.rpm`

**Comment by runcom** [comment]
> Specifically, docker-1.12.3-8.el7.x86_64.rpm
> Today I have access to docker-1.12.3-8 on Troy's repo on the OpenShift mirror. Will that have the fix?

@stevekuznetsov I don't know about Troy's repo - does that `-8` build number maps to any commit into the rhel dist-git? or could you tell me which commit (with `docker version` probably) does that docker have?

**Comment by runcom** [comment]
@stevekuznetsov you can find if the commit is in https://github.com/projectatomic/docker/commits/docker-1.12.3 - specifically https://github.com/projectatomic/docker/commit/47e22f22361b3e4a73479b20d1f35f237ed8faba is the commit which fixes this issue.

**Comment by stevekuznetsov** [comment]
Ok, looking at Brew it is in the release we have.
